import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { spotifyFetch, isSpotifyConnected } from "@/lib/spotify-client";
import path from "path";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { session_id, name, track_ids, description, cover_image, song_assignments } = body;

    if (!(await isSpotifyConnected())) {
      return NextResponse.json({ error: "Spotify not connected. Re-connect in Sources." }, { status: 401 });
    }

    // Create empty playlist
    const createRes = await spotifyFetch(`/me/playlists`, {
      method: "POST",
      body: JSON.stringify({ name, public: false, description: description ?? "Generated by Soma" }),
    });

    if (!createRes.ok) {
      const err = await createRes.text().catch(() => "");
      return NextResponse.json({ error: `Spotify ${createRes.status}: ${err.slice(0, 200)}` }, { status: 502 });
    }

    const playlist = await createRes.json();

    // Add tracks in batches of 100
    const ids: string[] = track_ids ?? [];
    for (let i = 0; i < ids.length; i += 100) {
      const batch = ids.slice(i, i + 100).map((id) => `spotify:track:${id}`);
      await spotifyFetch(`/playlists/${playlist.id}/items`, {
        method: "POST",
        body: JSON.stringify({ uris: batch }),
      });
    }

    // Upload cover image if provided (base64 JPEG, max 256KB)
    if (cover_image) {
      try {
        const sharp = (await import("sharp")).default;
        let imgBase64: string;
        if (cover_image === "soma") {
          const imgPath = path.join(process.cwd(), "public", "soma-icon.png");
          const jpegBuf = await sharp(imgPath).jpeg({ quality: 90 }).toBuffer();
          imgBase64 = jpegBuf.toString("base64");
        } else {
          imgBase64 = cover_image;
        }
        const imgRes = await spotifyFetch(`/playlists/${playlist.id}/images`, {
          method: "PUT",
          headers: { "Content-Type": "image/jpeg" },
          body: imgBase64,
        });
        if (!imgRes.ok) {
          console.warn("Cover image upload failed:", imgRes.status, await imgRes.text().catch(() => ""));
        }
      } catch (e) {
        console.warn("Cover image processing error:", e);
      }
    }

    // Update session with playlist info
    if (session_id) {
      const sql = getDb();
      await sql`
        UPDATE playlist_sessions
        SET
          spotify_playlist_id = ${playlist.id as string},
          spotify_playlist_url = ${(playlist.external_urls?.spotify as string) ?? null},
          updated_at = NOW()
        WHERE id = ${session_id}
      `;
      if (song_assignments) {
        await sql`
          UPDATE playlist_sessions
          SET song_assignments = ${JSON.stringify(song_assignments)}::jsonb
          WHERE id = ${session_id}
        `;
      }
    }

    return NextResponse.json({
      playlist_id: playlist.id,
      playlist_url: playlist.external_urls?.spotify,
    });
  } catch (err) {
    console.error("[POST /api/playlist/spotify/create] Error:", err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}

export async function PUT(req: NextRequest) {
  const { playlist_id, session_id, track_ids, song_assignments } = await req.json();

  if (!(await isSpotifyConnected())) {
    return NextResponse.json({ error: "Spotify not connected. Re-connect in Sources." }, { status: 401 });
  }

  if (!playlist_id) {
    return NextResponse.json({ error: "playlist_id required" }, { status: 400 });
  }

  const ids: string[] = track_ids ?? [];

  // Replace all tracks: first batch = PUT (replaces), remaining = POST (appends)
  const firstBatch = ids.slice(0, 100).map((id) => `spotify:track:${id}`);
  const replaceRes = await spotifyFetch(`/playlists/${playlist_id}/items`, {
    method: "PUT",
    body: JSON.stringify({ uris: firstBatch }),
  });
  if (!replaceRes.ok) {
    const err = await replaceRes.text();
    return NextResponse.json({ error: `Failed to update playlist: ${err}` }, { status: 500 });
  }

  // Append remaining batches
  for (let i = 100; i < ids.length; i += 100) {
    const batch = ids.slice(i, i + 100).map((id) => `spotify:track:${id}`);
    await spotifyFetch(`/playlists/${playlist_id}/items`, {
      method: "POST",
      body: JSON.stringify({ uris: batch }),
    });
  }

  // Update session record
  if (session_id) {
    const sql = getDb();
    await sql`
      UPDATE playlist_sessions
      SET updated_at = NOW()
      WHERE id = ${session_id}
    `;
    // Persist current song_assignments to session for future restore
    if (song_assignments) {
      await sql`
        UPDATE playlist_sessions
        SET song_assignments = ${JSON.stringify(song_assignments)}::jsonb
        WHERE id = ${session_id}
      `;
    }
  }

  // Fetch playlist URL (it doesn't change on update)
  const playlistRes = await spotifyFetch(`/playlists/${playlist_id}?fields=external_urls`);
  const playlistData = playlistRes.ok ? await playlistRes.json() : null;

  return NextResponse.json({
    playlist_id,
    playlist_url: (playlistData as { external_urls?: { spotify?: string } } | null)?.external_urls?.spotify,
  });
}
