import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { spotifyFetch, getSpotifyProfile } from "@/lib/spotify-client";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const { session_id, name, track_ids } = await req.json();

  const profile = await getSpotifyProfile();
  if (!profile) {
    return NextResponse.json({ error: "Spotify not connected" }, { status: 401 });
  }

  // Create empty playlist
  const createRes = await spotifyFetch(`/users/${profile.id}/playlists`, {
    method: "POST",
    body: JSON.stringify({ name, public: false, description: "Generated by Soma" }),
  });

  if (!createRes.ok) {
    const err = await createRes.text();
    return NextResponse.json({ error: `Failed to create playlist: ${err}` }, { status: 500 });
  }

  const playlist = await createRes.json();

  // Add tracks in batches of 100
  const ids: string[] = track_ids ?? [];
  for (let i = 0; i < ids.length; i += 100) {
    const batch = ids.slice(i, i + 100).map((id) => `spotify:track:${id}`);
    await spotifyFetch(`/playlists/${playlist.id}/tracks`, {
      method: "POST",
      body: JSON.stringify({ uris: batch }),
    });
  }

  // Update session with playlist info
  if (session_id) {
    const sql = getDb();
    await sql`
      UPDATE playlist_sessions
      SET
        spotify_playlist_id = ${playlist.id as string},
        spotify_playlist_url = ${(playlist.external_urls?.spotify as string) ?? null},
        updated_at = NOW()
      WHERE id = ${session_id}
    `;
  }

  return NextResponse.json({
    playlist_id: playlist.id,
    playlist_url: playlist.external_urls?.spotify,
  });
}
